// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Balance
	TransferRequest
	TransferResult
	AddressInfo
	TransactionInfoRequest
	TransactionInfo
	AddressInfoRequest
	WalletInfo
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Balance struct {
	PropertyID int32  `protobuf:"varint,1,opt,name=propertyID" json:"propertyID,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Balance    string `protobuf:"bytes,3,opt,name=balance" json:"balance,omitempty"`
	Reserved   string `protobuf:"bytes,4,opt,name=reserved" json:"reserved,omitempty"`
	Frozen     string `protobuf:"bytes,5,opt,name=frozen" json:"frozen,omitempty"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Balance) GetPropertyID() int32 {
	if m != nil {
		return m.PropertyID
	}
	return 0
}

func (m *Balance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Balance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Balance) GetReserved() string {
	if m != nil {
		return m.Reserved
	}
	return ""
}

func (m *Balance) GetFrozen() string {
	if m != nil {
		return m.Frozen
	}
	return ""
}

type TransferRequest struct {
	Fromaddress string `protobuf:"bytes,1,opt,name=fromaddress" json:"fromaddress,omitempty"`
	Toaddress   string `protobuf:"bytes,2,opt,name=toaddress" json:"toaddress,omitempty"`
	Propertyid  string `protobuf:"bytes,3,opt,name=propertyid" json:"propertyid,omitempty"`
	Amount      string `protobuf:"bytes,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *TransferRequest) Reset()                    { *m = TransferRequest{} }
func (m *TransferRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()               {}
func (*TransferRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransferRequest) GetFromaddress() string {
	if m != nil {
		return m.Fromaddress
	}
	return ""
}

func (m *TransferRequest) GetToaddress() string {
	if m != nil {
		return m.Toaddress
	}
	return ""
}

func (m *TransferRequest) GetPropertyid() string {
	if m != nil {
		return m.Propertyid
	}
	return ""
}

func (m *TransferRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type TransferResult struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *TransferResult) Reset()                    { *m = TransferResult{} }
func (m *TransferResult) String() string            { return proto.CompactTextString(m) }
func (*TransferResult) ProtoMessage()               {}
func (*TransferResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransferResult) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type AddressInfo struct {
	Address  string     `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Balances []*Balance `protobuf:"bytes,2,rep,name=balances" json:"balances,omitempty"`
}

func (m *AddressInfo) Reset()                    { *m = AddressInfo{} }
func (m *AddressInfo) String() string            { return proto.CompactTextString(m) }
func (*AddressInfo) ProtoMessage()               {}
func (*AddressInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddressInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddressInfo) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type TransactionInfoRequest struct {
	TxID string `protobuf:"bytes,1,opt,name=txID" json:"txID,omitempty"`
}

func (m *TransactionInfoRequest) Reset()                    { *m = TransactionInfoRequest{} }
func (m *TransactionInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*TransactionInfoRequest) ProtoMessage()               {}
func (*TransactionInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TransactionInfoRequest) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

type TransactionInfo struct {
	TxID             string `protobuf:"bytes,1,opt,name=txID" json:"txID,omitempty"`
	SendingAddress   string `protobuf:"bytes,2,opt,name=sendingAddress" json:"sendingAddress,omitempty"`
	ReferencAaddress string `protobuf:"bytes,3,opt,name=referencAaddress" json:"referencAaddress,omitempty"`
	IsMine           bool   `protobuf:"varint,4,opt,name=isMine" json:"isMine,omitempty"`
	Confirmations    int32  `protobuf:"varint,5,opt,name=confirmations" json:"confirmations,omitempty"`
	Fee              string `protobuf:"bytes,6,opt,name=fee" json:"fee,omitempty"`
	BlockTime        int32  `protobuf:"varint,7,opt,name=blockTime" json:"blockTime,omitempty"`
	Valid            bool   `protobuf:"varint,8,opt,name=valid" json:"valid,omitempty"`
	PositioninBlock  int32  `protobuf:"varint,9,opt,name=positioninBlock" json:"positioninBlock,omitempty"`
	Version          int32  `protobuf:"varint,10,opt,name=version" json:"version,omitempty"`
	TypeInt          int32  `protobuf:"varint,11,opt,name=typeInt" json:"typeInt,omitempty"`
	Type             string `protobuf:"bytes,12,opt,name=type" json:"type,omitempty"`
}

func (m *TransactionInfo) Reset()                    { *m = TransactionInfo{} }
func (m *TransactionInfo) String() string            { return proto.CompactTextString(m) }
func (*TransactionInfo) ProtoMessage()               {}
func (*TransactionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TransactionInfo) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *TransactionInfo) GetSendingAddress() string {
	if m != nil {
		return m.SendingAddress
	}
	return ""
}

func (m *TransactionInfo) GetReferencAaddress() string {
	if m != nil {
		return m.ReferencAaddress
	}
	return ""
}

func (m *TransactionInfo) GetIsMine() bool {
	if m != nil {
		return m.IsMine
	}
	return false
}

func (m *TransactionInfo) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *TransactionInfo) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *TransactionInfo) GetBlockTime() int32 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *TransactionInfo) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *TransactionInfo) GetPositioninBlock() int32 {
	if m != nil {
		return m.PositioninBlock
	}
	return 0
}

func (m *TransactionInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TransactionInfo) GetTypeInt() int32 {
	if m != nil {
		return m.TypeInt
	}
	return 0
}

func (m *TransactionInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type AddressInfoRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *AddressInfoRequest) Reset()                    { *m = AddressInfoRequest{} }
func (m *AddressInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*AddressInfoRequest) ProtoMessage()               {}
func (*AddressInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddressInfoRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type WalletInfo struct {
	Balances []*Balance `protobuf:"bytes,1,rep,name=balances" json:"balances,omitempty"`
}

func (m *WalletInfo) Reset()                    { *m = WalletInfo{} }
func (m *WalletInfo) String() string            { return proto.CompactTextString(m) }
func (*WalletInfo) ProtoMessage()               {}
func (*WalletInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *WalletInfo) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterType((*Balance)(nil), "api.Balance")
	proto.RegisterType((*TransferRequest)(nil), "api.TransferRequest")
	proto.RegisterType((*TransferResult)(nil), "api.TransferResult")
	proto.RegisterType((*AddressInfo)(nil), "api.AddressInfo")
	proto.RegisterType((*TransactionInfoRequest)(nil), "api.TransactionInfoRequest")
	proto.RegisterType((*TransactionInfo)(nil), "api.TransactionInfo")
	proto.RegisterType((*AddressInfoRequest)(nil), "api.AddressInfoRequest")
	proto.RegisterType((*WalletInfo)(nil), "api.WalletInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ExampleAPI service

type ExampleAPIClient interface {
	// NewAddress returns new generated address
	NewAddress(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*AddressInfo, error)
	// Transfer transfers funcs to an address
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResult, error)
	// ListAddresses lists existing addresses for account
	ListAddresses(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (ExampleAPI_ListAddressesClient, error)
	// GetTransactionInfo returns info about transaction
	GetTransactionInfo(ctx context.Context, in *TransactionInfoRequest, opts ...grpc.CallOption) (*TransactionInfo, error)
	// GetWalletInfo returns info about wallet
	GetWalletInfo(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*WalletInfo, error)
	// GetAddressInfo returns info about address
	GetAddressInfo(ctx context.Context, in *AddressInfoRequest, opts ...grpc.CallOption) (*AddressInfo, error)
}

type exampleAPIClient struct {
	cc *grpc.ClientConn
}

func NewExampleAPIClient(cc *grpc.ClientConn) ExampleAPIClient {
	return &exampleAPIClient{cc}
}

func (c *exampleAPIClient) NewAddress(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*AddressInfo, error) {
	out := new(AddressInfo)
	err := grpc.Invoke(ctx, "/api.ExampleAPI/NewAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleAPIClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResult, error) {
	out := new(TransferResult)
	err := grpc.Invoke(ctx, "/api.ExampleAPI/Transfer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleAPIClient) ListAddresses(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (ExampleAPI_ListAddressesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ExampleAPI_serviceDesc.Streams[0], c.cc, "/api.ExampleAPI/ListAddresses", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleAPIListAddressesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ExampleAPI_ListAddressesClient interface {
	Recv() (*AddressInfo, error)
	grpc.ClientStream
}

type exampleAPIListAddressesClient struct {
	grpc.ClientStream
}

func (x *exampleAPIListAddressesClient) Recv() (*AddressInfo, error) {
	m := new(AddressInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleAPIClient) GetTransactionInfo(ctx context.Context, in *TransactionInfoRequest, opts ...grpc.CallOption) (*TransactionInfo, error) {
	out := new(TransactionInfo)
	err := grpc.Invoke(ctx, "/api.ExampleAPI/GetTransactionInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleAPIClient) GetWalletInfo(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*WalletInfo, error) {
	out := new(WalletInfo)
	err := grpc.Invoke(ctx, "/api.ExampleAPI/GetWalletInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleAPIClient) GetAddressInfo(ctx context.Context, in *AddressInfoRequest, opts ...grpc.CallOption) (*AddressInfo, error) {
	out := new(AddressInfo)
	err := grpc.Invoke(ctx, "/api.ExampleAPI/GetAddressInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExampleAPI service

type ExampleAPIServer interface {
	// NewAddress returns new generated address
	NewAddress(context.Context, *google_protobuf1.Empty) (*AddressInfo, error)
	// Transfer transfers funcs to an address
	Transfer(context.Context, *TransferRequest) (*TransferResult, error)
	// ListAddresses lists existing addresses for account
	ListAddresses(*google_protobuf1.Empty, ExampleAPI_ListAddressesServer) error
	// GetTransactionInfo returns info about transaction
	GetTransactionInfo(context.Context, *TransactionInfoRequest) (*TransactionInfo, error)
	// GetWalletInfo returns info about wallet
	GetWalletInfo(context.Context, *google_protobuf1.Empty) (*WalletInfo, error)
	// GetAddressInfo returns info about address
	GetAddressInfo(context.Context, *AddressInfoRequest) (*AddressInfo, error)
}

func RegisterExampleAPIServer(s *grpc.Server, srv ExampleAPIServer) {
	s.RegisterService(&_ExampleAPI_serviceDesc, srv)
}

func _ExampleAPI_NewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleAPIServer).NewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ExampleAPI/NewAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleAPIServer).NewAddress(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleAPI_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleAPIServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ExampleAPI/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleAPIServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleAPI_ListAddresses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExampleAPIServer).ListAddresses(m, &exampleAPIListAddressesServer{stream})
}

type ExampleAPI_ListAddressesServer interface {
	Send(*AddressInfo) error
	grpc.ServerStream
}

type exampleAPIListAddressesServer struct {
	grpc.ServerStream
}

func (x *exampleAPIListAddressesServer) Send(m *AddressInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _ExampleAPI_GetTransactionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleAPIServer).GetTransactionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ExampleAPI/GetTransactionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleAPIServer).GetTransactionInfo(ctx, req.(*TransactionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleAPI_GetWalletInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleAPIServer).GetWalletInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ExampleAPI/GetWalletInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleAPIServer).GetWalletInfo(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleAPI_GetAddressInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleAPIServer).GetAddressInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ExampleAPI/GetAddressInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleAPIServer).GetAddressInfo(ctx, req.(*AddressInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ExampleAPI",
	HandlerType: (*ExampleAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewAddress",
			Handler:    _ExampleAPI_NewAddress_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _ExampleAPI_Transfer_Handler,
		},
		{
			MethodName: "GetTransactionInfo",
			Handler:    _ExampleAPI_GetTransactionInfo_Handler,
		},
		{
			MethodName: "GetWalletInfo",
			Handler:    _ExampleAPI_GetWalletInfo_Handler,
		},
		{
			MethodName: "GetAddressInfo",
			Handler:    _ExampleAPI_GetAddressInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAddresses",
			Handler:       _ExampleAPI_ListAddresses_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6a, 0x1b, 0x3b,
	0x14, 0x66, 0xe2, 0x9f, 0xd8, 0xc7, 0xf1, 0xcf, 0x55, 0x8c, 0x33, 0x77, 0x12, 0x42, 0xee, 0x10,
	0x2e, 0x26, 0x14, 0xbb, 0x4d, 0xa1, 0x8b, 0xee, 0x1c, 0x1a, 0x82, 0xa1, 0x2d, 0xe9, 0x90, 0x52,
	0xe8, 0xa2, 0x20, 0xdb, 0x67, 0x12, 0x91, 0xb1, 0x34, 0x9d, 0x91, 0x9d, 0xb8, 0x21, 0x9b, 0xee,
	0x4a, 0x97, 0x7d, 0x8d, 0xbe, 0x4d, 0x5f, 0xa1, 0xfb, 0xbe, 0x42, 0x91, 0x46, 0x13, 0x4f, 0x26,
	0x49, 0xa1, 0x3b, 0x9d, 0x73, 0xa4, 0x4f, 0x9f, 0xbe, 0xef, 0x1c, 0x41, 0x3d, 0xc6, 0x68, 0xce,
	0xc6, 0xd8, 0x0b, 0x23, 0x21, 0x05, 0x29, 0xd0, 0x90, 0x39, 0x5b, 0xa7, 0x42, 0x9c, 0x06, 0xd8,
	0xa7, 0x21, 0xeb, 0x53, 0xce, 0x85, 0xa4, 0x92, 0x09, 0x1e, 0x27, 0x5b, 0x9c, 0x4d, 0x53, 0xd5,
	0xd1, 0x68, 0xe6, 0xf7, 0x71, 0x1a, 0xca, 0x45, 0x52, 0x74, 0xbf, 0x5a, 0xb0, 0x7a, 0x40, 0x03,
	0xca, 0xc7, 0x48, 0xb6, 0x01, 0xc2, 0x48, 0x84, 0x18, 0xc9, 0xc5, 0xf0, 0x85, 0x6d, 0xed, 0x58,
	0xdd, 0x92, 0x97, 0xc9, 0x10, 0x02, 0x45, 0x4e, 0xa7, 0x68, 0xaf, 0xec, 0x58, 0xdd, 0xaa, 0xa7,
	0xd7, 0xc4, 0x86, 0xd5, 0x51, 0x72, 0xdc, 0x2e, 0xe8, 0x74, 0x1a, 0x12, 0x07, 0x2a, 0x11, 0x2a,
	0xb2, 0x38, 0xb1, 0x8b, 0xba, 0x74, 0x13, 0x93, 0x0e, 0x94, 0xfd, 0x48, 0x7c, 0x42, 0x6e, 0x97,
	0x74, 0xc5, 0x44, 0xee, 0x17, 0x0b, 0x9a, 0x27, 0x11, 0xe5, 0xb1, 0x8f, 0x91, 0x87, 0x1f, 0x67,
	0x18, 0x4b, 0xb2, 0x03, 0x35, 0x3f, 0x12, 0x53, 0x3a, 0x99, 0x44, 0x18, 0xc7, 0x9a, 0x56, 0xd5,
	0xcb, 0xa6, 0xc8, 0x16, 0x54, 0xa5, 0x48, 0xeb, 0x09, 0xb9, 0x65, 0x22, 0xfb, 0x2a, 0x36, 0x31,
	0x24, 0x33, 0x19, 0xc5, 0x85, 0x4e, 0xc5, 0x8c, 0x4b, 0xc3, 0xd2, 0x44, 0xee, 0x2e, 0x34, 0x96,
	0x54, 0xe2, 0x59, 0x20, 0xd5, 0xfb, 0xcf, 0x68, 0x7c, 0x66, 0x28, 0xe8, 0xb5, 0xfb, 0x06, 0x6a,
	0x83, 0xe4, 0xa2, 0x21, 0xf7, 0x85, 0x92, 0xe3, 0x36, 0xd1, 0x34, 0x24, 0x5d, 0xa8, 0x18, 0x65,
	0x14, 0xc7, 0x42, 0xb7, 0xb6, 0xbf, 0xd6, 0xa3, 0x21, 0xeb, 0x19, 0xf1, 0xbd, 0x9b, 0xaa, 0xfb,
	0x08, 0x3a, 0xfa, 0x62, 0x3a, 0x56, 0x2e, 0x2a, 0xd8, 0x54, 0x0a, 0x02, 0x45, 0x79, 0x69, 0xac,
	0xa9, 0x7a, 0x7a, 0xed, 0xfe, 0x5a, 0x31, 0x92, 0x2d, 0xb7, 0xdf, 0xb7, 0x8f, 0xfc, 0x0f, 0x8d,
	0x18, 0xf9, 0x84, 0xf1, 0xd3, 0xc1, 0x2d, 0xa5, 0x72, 0x59, 0xb2, 0x07, 0xad, 0x08, 0x7d, 0x8c,
	0x90, 0x8f, 0x07, 0xe9, 0x53, 0x12, 0xd1, 0xee, 0xe4, 0x95, 0x74, 0x2c, 0x7e, 0xc5, 0x38, 0x6a,
	0xe9, 0x2a, 0x9e, 0x89, 0xc8, 0x2e, 0xd4, 0xc7, 0x82, 0xfb, 0x2c, 0x9a, 0x26, 0x8d, 0xa8, 0x5d,
	0x2e, 0x79, 0xb7, 0x93, 0xa4, 0x05, 0x05, 0x1f, 0xd1, 0x2e, 0x6b, 0x70, 0xb5, 0x54, 0x46, 0x8e,
	0x02, 0x31, 0x3e, 0x3f, 0x61, 0x53, 0xb4, 0x57, 0xf5, 0x99, 0x65, 0x82, 0xb4, 0xa1, 0x34, 0xa7,
	0x01, 0x9b, 0xd8, 0x15, 0x7d, 0x59, 0x12, 0x90, 0x2e, 0x34, 0x43, 0x11, 0x33, 0x05, 0xc9, 0xf8,
	0x81, 0xda, 0x6c, 0x57, 0xf5, 0xc9, 0x7c, 0x5a, 0x79, 0x33, 0xc7, 0x28, 0x66, 0x82, 0xdb, 0xa0,
	0x77, 0xa4, 0xa1, 0xaa, 0xc8, 0x45, 0x88, 0x43, 0x2e, 0xed, 0x5a, 0x52, 0x31, 0xa1, 0x56, 0x72,
	0x11, 0xa2, 0xbd, 0x66, 0x94, 0x5c, 0x84, 0xe8, 0xf6, 0x80, 0x64, 0x2c, 0x4f, 0xbd, 0x79, 0xd0,
	0x79, 0xf7, 0x19, 0xc0, 0x3b, 0x1a, 0x04, 0x28, 0xb5, 0x37, 0xd9, 0x3e, 0xb0, 0xfe, 0xd4, 0x07,
	0xfb, 0xdf, 0x8b, 0x00, 0x87, 0x97, 0x74, 0x1a, 0x06, 0x38, 0x38, 0x1e, 0x12, 0x0f, 0xe0, 0x35,
	0x5e, 0xa4, 0x36, 0x75, 0x7a, 0xc9, 0x54, 0xf7, 0xd2, 0xa9, 0xee, 0x1d, 0xaa, 0xa9, 0x76, 0x5a,
	0x1a, 0x2c, 0xc3, 0xcf, 0x75, 0x3e, 0xff, 0xf8, 0xf9, 0x6d, 0xa5, 0xed, 0x36, 0xf5, 0xf7, 0x30,
	0x7f, 0xd2, 0x37, 0xbc, 0x9e, 0x5b, 0x7b, 0xe4, 0x2d, 0x54, 0xd2, 0x1e, 0x27, 0x6d, 0x7d, 0x32,
	0x37, 0x7d, 0xce, 0x7a, 0x2e, 0xab, 0x06, 0xc1, 0xdd, 0xd6, 0x90, 0xb6, 0xbb, 0x9e, 0x42, 0xca,
	0x65, 0x03, 0x2a, 0xd8, 0x13, 0xa8, 0xbf, 0x64, 0xb1, 0x34, 0x2c, 0xf0, 0x6f, 0xd8, 0x6e, 0x68,
	0xe8, 0x7f, 0x48, 0x9e, 0xed, 0x63, 0x8b, 0x9c, 0x03, 0x39, 0x42, 0x99, 0xef, 0xf5, 0xcd, 0x25,
	0xc1, 0x3b, 0x03, 0xe3, 0xb4, 0xef, 0x2b, 0xba, 0xae, 0xbe, 0x63, 0x8b, 0x38, 0xf7, 0xd0, 0xef,
	0x5f, 0xa9, 0x69, 0xb9, 0x26, 0xc7, 0x50, 0x3f, 0x42, 0x99, 0xf1, 0xed, 0xa1, 0x27, 0x34, 0xf5,
	0x15, 0xcb, 0x8d, 0x6e, 0x47, 0xa3, 0xb7, 0x48, 0x23, 0x45, 0xbf, 0xd0, 0x35, 0xf2, 0x01, 0x1a,
	0x47, 0x28, 0xb3, 0x9f, 0xc5, 0x46, 0xfe, 0xf5, 0x29, 0xed, 0xbb, 0xb2, 0xfc, 0xa7, 0x41, 0x37,
	0xc9, 0xbf, 0x39, 0x59, 0xfa, 0x57, 0x66, 0x71, 0x7d, 0x50, 0x79, 0x5f, 0xd6, 0xbf, 0x6b, 0x34,
	0x2a, 0x6b, 0x8a, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x24, 0x33, 0xb5, 0x2b, 0x06,
	0x00, 0x00,
}
